spring:
  datasource:
## default connection pool
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
## PostgreSQL
    username: familybudget
    password: *
    url: jdbc:postgresql://localhost:5432/postgres
## Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect